name: Build and Deploy to Azure with Persistent Storage

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Delete Existing Container (if it exists)
      - name: Delete Existing Container Instance
        run: |
          az container delete \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name my-container-app \
            --yes || echo "Container does not exist, skipping deletion."

      # Step 4: Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image to ACR
        run: |
          IMAGE_TAG=${{ secrets.REGISTRY_LOGIN_SERVER }}/my-container:${{ github.run_number }}
          docker build -t $IMAGE_TAG .
          docker push $IMAGE_TAG

      # Step 6: Deploy to Azure Container Instances with Persistent Storage
      - name: Deploy to Azure Container Instances with Persistent Storage
        run: |
          az container create \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name my-container-app \
            --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-container:${{ github.run_number }} \
            --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --registry-username ${{ secrets.REGISTRY_USERNAME }} \
            --registry-password ${{ secrets.REGISTRY_PASSWORD }} \
            --dns-name-label ${{ secrets.DNS_LABEL }}-${{ github.run_number }} \
            --location swedencentral \
            --ports 80 \
            --azure-file-volume-account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
            --azure-file-volume-account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
            --azure-file-volume-share-name ${{ secrets.FILE_SHARE_NAME }} \
            --azure-file-volume-mount-path /mnt/data

      # Debugging Variables (Optional)
      - name: Debugging Variables
        run: |
          echo "Storage Account Name: ${{ secrets.STORAGE_ACCOUNT_NAME }}"
          echo "File Share Name: ${{ secrets.FILE_SHARE_NAME }}"
