on: [push]
name: GettingStarted_Container_Workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: 'Checkout GitHub Action'
      uses: actions/checkout@v3

    # Step 2: Login to Azure CLI
    - name: 'Login to Azure CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3: Login to Azure Container Registry
    - name: 'Login to Azure Container Registry'
      run: |
        docker login ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --username ${{ secrets.REGISTRY_USERNAME }} \
          --password ${{ secrets.REGISTRY_PASSWORD }}

    # Step 4: Build and Push Docker Image
    - name: 'Build and Push Docker Image'
      run: |
        docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-app:${{ github.run_number }} \
        && docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-app:${{ github.run_number }}

    # Step 5: Deploy to Azure Container Instances
    - name: 'Deploy to Azure Container Instances'
      run: |
        az container create \
          --resource-group ${{ secrets.RESOURCE_GROUP }} \
          --name my-container \
          --image ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-app:${{ github.run_number }} \
          --dns-name-label my-app-${{ github.run_number }} \
          --ports 3000 \
          --registry-login-server ${{ secrets.REGISTRY_LOGIN_SERVER }} \
          --registry-username ${{ secrets.REGISTRY_USERNAME }} \
          --registry-password ${{ secrets.REGISTRY_PASSWORD }}
