name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Login to Azure
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Login to Azure Container Registry (ACR)
      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      # Step 4: Build and Push Docker Image
      - name: Build and Push Docker Image to ACR
        run: |
          IMAGE_TAG=${{ secrets.REGISTRY_LOGIN_SERVER }}/my-container:${{ github.run_number }}
          docker build . -t $IMAGE_TAG
          docker push $IMAGE_TAG

      # Step 5: Deploy to Azure Container Instances (ACI)
      - name: Deploy to Azure Container Instances
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: ${{ secrets.DNS_LABEL }}-${{ github.run_number }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/my-container:${{ github.run_number }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          name: my-container-app
          location: westus
          ports: '80'
