name: Azure Storage File Upload Workflow

on:
  push:
    branches:
      - main

jobs:
  upload-to-storage:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using a Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Upload a file to the Azure Storage container
      - name: Upload File to Azure Container
        run: |
          # Retrieve the storage account key
          STORAGE_KEY=$(az storage account keys list \
            --account-name <your-storage-account-name> \
            --query "[0].value" -o tsv)

          # Upload the file to the specified blob container
          az storage blob upload \
            --container-name <your-container-name> \
            --file ./<path-to-local-file> \
            --name <blob-name> \
            --account-name <your-storage-account-name> \
            --account-key $STORAGE_KEY
        env:
          AZURE_STORAGE_ACCOUNT: <your-storage-account-name>

      # Step 4: Confirm upload (optional)
      - name: List blobs in container
        run: |
          az storage blob list \
            --container-name <your-container-name> \
            --account-name <your-storage-account-name> \
            --account-key $(az storage account keys list \
              --account-name <your-storage-account-name> \
              --query "[0].value" -o tsv) \
            --output table
