name: Azure File Share Upload Workflow

on:
  push:
    branches:
      - main

jobs:
  upload-to-fileshare:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Azure using a Service Principal
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Retrieve data from the container app
      - name: Retrieve Data from Container App
        run: |
          # API URL of the container app
          CONTAINER_API_URL="http://container-27.swedencentral.azurecontainer.io:3000/api/items"
          
          # Fetch data using curl and save to a temporary file
          curl -s $CONTAINER_API_URL > data.json

      # Step 4: Upload data to Azure File Share
      - name: Upload Data to Azure File Share
        run: |
          # Retrieve the storage account key
          STORAGE_KEY=$(az storage account keys list \
            --account-name mystorageaccount1283 \
            --query "[0].value" -o tsv)

          # Install CIFS utilities (if not already installed)
          sudo apt-get update && sudo apt-get install -y cifs-utils

          # Mount the file share locally
          sudo mkdir -p /mnt/azurefileshare
          sudo mount -t cifs //mystorageaccount1283.file.core.windows.net/myfileshare /mnt/azurefileshare \
            -o vers=3.0,username=mystorageaccount1283,password=$STORAGE_KEY,dir_mode=0777,file_mode=0777,sec=ntlmssp

          # Save the retrieved data to the file share
          sudo cp ./data.json /mnt/azurefileshare/

          # Unmount the file share
          sudo umount /mnt/azurefileshare
