on: [push]
name: Existing_Container_and_Storage_Workflow

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      # Step 2: Login to Azure CLI
      - name: 'Login to Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 3: Upload Sample File to Existing Azure File Share
      - name: 'Upload Sample File to Azure File Share'
        run: |
          # Use secrets for storage details
          STORAGE_ACCOUNT_NAME=${{ secrets.STORAGE_ACCOUNT_NAME }}
          FILE_SHARE_NAME=${{ secrets.FILE_SHARE_NAME }}
          STORAGE_ACCOUNT_KEY=${{ secrets.STORAGE_ACCOUNT_KEY }}

          # Create a sample file
          echo "Sample data for Azure File Share" > sample-data.txt

          # Upload the file to Azure File Share
          az storage file upload \
            --share-name $FILE_SHARE_NAME \
            --source sample-data.txt \
            --account-name $STORAGE_ACCOUNT_NAME \
            --account-key $STORAGE_ACCOUNT_KEY

      # Step 4: Link Existing Container to File Storage
      - name: 'Link Existing Container to File Storage'
        run: |
          az container update \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.CONTAINER_NAME }} \
            --azure-file-volume-share-name ${{ secrets.FILE_SHARE_NAME }} \
            --azure-file-volume-account-name ${{ secrets.STORAGE_ACCOUNT_NAME }} \
            --azure-file-volume-account-key ${{ secrets.STORAGE_ACCOUNT_KEY }} \
            --azure-file-volume-mount-path ${{ secrets.STORAGE_PATH }}
